In [2]:
import pandas as pd
import numpy as np

In [3]:
customer_dic = {
'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace','Hyemin'],
'comment_length': [150, 200, 50, 300, 120, 180, 75, 160],
'likes': [25, 30, 10, 45, 20, 35, 5, 28],
'is_spam': [False, False, True, np.nan, False, True, np.nan, False],
'has_image': [True, False, True, True, False, False, True, True]
}

In [ ]:
# 1번 customer_dic를 데이터프레임으로 만들어주기
customer = pd.DataFrame(customer_dic)
customer

      name  comment_length  likes is_spam  has_image
0    Alice             150     25   False       True
1      Bob             200     30   False      False
2  Charlie              50     10    True       True
3    David             300     45     NaN       True
4      Eve             120     20   False      False
5    Frank             180     35    True      False
6    Grace              75      5     NaN       True
7   Hyemin             160     28   False       True

In [61]:
# 2번 is_spam 결측치 확인하기 
#is_spam 결측치를 False로 대체하기
customer['is_spam'] = customer['is_spam'].fillna('False')
customer['is_spam'] = customer['is_spam'].replace('False', False)
customer.info()

customer

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            8 non-null      str
 1   comment_length  8 non-null      int64
 2   likes           8 non-null      int64
 3   is_spam         8 non-null      object
 4   has_image       8 non-null      bool
dtypes: bool(1), int64(2), object(1), str(1)
memory usage: 396.0+ bytes

      name  comment_length  likes is_spam  has_image
0    Alice             150     25   False       True
1      Bob             200     30   False      False
2  Charlie              50     10    True       True
3    David             300     45   False       True
4      Eve             120     20   False      False
5    Frank             180     35    True      False
6    Grace              75      5   False       True
7   Hyemin             160     28   False       True

In [ ]:
# 3번 has_image 열을 기준으로 이미지가 포함된 댓글과 포함되지 않은 댓글의 평균 likes를 구하세요 
customer.groupby('has_image')['likes'].mean()

has_image
False    28.333333
True     22.600000
Name: likes, dtype: float64

In [62]:
# 4번 상품을 받을 고객의 이름을 구하세요 조건은 아래와 같습니다
customer.query('comment_length >= 100 & likes >= 20 & is_spam == False & has_image == True')

     name  comment_length  likes is_spam  has_image
0   Alice             150     25   False       True
3   David             300     45   False       True
7  Hyemin             160     28   False       True

In [51]:
# 5번 고객 데이터에서 이름만 추출하여 시리즈 형태로 생성하고 하위 3줄의 데이터를 출력세요
pd.Series(customer['name']).tail(3)

5     Frank
6     Grace
7    Hyemin
Name: name, dtype: str

In [ ]:
# 6번 고객 데이터를 to_csv() 함수를 사용하여 'customer.csv' 파일로 저장하세요
customer.to_csv('customer.csv', index=False)

In [55]:
# 7번 저장된 고객 데이터를 불러와 상위 5개 데이터를 확인하세요

pd.read_csv('./customer.csv').head()

      name  comment_length  likes  is_spam  has_image
0    Alice             150     25    False       True
1      Bob             200     30    False      False
2  Charlie              50     10     True       True
3    David             300     45    False       True
4      Eve             120     20    False      False