# Pandas 1일차

In [5]:
# 모델을 만들때, 학습을 시킬때 pandas를 쓰지 않는다
# 데이터를 분석할때 자주 사용하는것이 판다스 이다 데이터 분석 <<<<< 판다스
# 최종 목표는 ai agent로 사업만들기 
# 판다스도 엑셀이다. 데이터베이스의 테이블이다 행과 열에 최적화 되어있다 >> 2차원 배열

In [6]:
# 시리즈가 있고 데이터 프레임이 있다. 1차원 배열 = 시리즈
# 넘파이는 어레이였으면 판다스는 "데이터프레임"<< 그냥 외워

In [7]:
import pandas as pd

In [8]:
series_data = pd.Series([True, 3.14, 'ABC'])
print(type(series_data))
print(series_data)

<class 'pandas.Series'>
0    True
1    3.14
2     ABC
dtype: object

In [9]:
# 컬럼내의 키 밸류 값으로 지정을 한다
df = pd.DataFrame({'c0' : [1,2,3], 'c1': [4,5,6]})
print(type(df))
df

<class 'pandas.DataFrame'>

   c0  c1
0   1   4
1   2   5
2   3   6

In [10]:
import numpy as np

dict_netflix = {
    'show_id':[1, 2, 3, 4, 5, 6, 7, 8],
    'type':['TV Show', 'TV Show', 'Movie', 'Movie', 'Movie', 'TV Show', 'Movie','Movie'],
    'title':['Squid Game', 'Stranger Things', 'Sherlock Holmes', 'Iron Man & Captain America: Heroes United', 'Bird Box', 'Anne with an E', 'About Time','Inception'],
    'director':[np.nan, np.nan, 'Guy Ritchie', 'Leo Riley', 'Susanne Bier', np.nan, 'Richard Curtis', 'Christopher Nolan'],
    'cast':['Lee Jung-jae', 'Winona Ryder', 'Robert Downey Jr', 'Adrian Pasdar', 'Sandra Bullock','Amybeth McNulty', 'Domhnall Gleeson', 'Leonardo DiCaprio'],
    'country':[np.nan, 'United States', 'United States, Germany', 'United States', 'United States', 'Canada', np.nan, 'United States'],
    'release_year':[2021, 2019, 2009, 2014, 2018, 2019, 2013, 2010],
    'duration':[300, 800, 128, 71, 124, 900, 123, 148],
    'listed_in':[np.nan, 'TV Horror', 'Action & Adventure', np.nan, np.nan, np.nan,np.nan, np.nan]}

netflix = pd.DataFrame(dict_netflix)
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [11]:
# csv를 가져오는 함수랑 내보내는 함수가 다르다 데이터를 불러옵니다(csv파일을)
# 파일 형식에 따라서 갖고오는 함수가 다르다
# ./ << 현재 폴더 
netflix = pd.read_csv("./netflix_selena.csv")
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [12]:
# 데이터셋 파일 저장하기(csv) >> 변수.to_csv(이름)
netflix.to_csv('netflix_new.csv', index=False)

In [13]:
# 열 이름 확인
list(netflix.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'release_year',
 'duration',
 'listed_in']

In [14]:
list(netflix.index)

[0, 1, 2, 3, 4, 5, 6, 7]

In [15]:
# 인덱스 바꾸기
netflix.index = ['1행', '2행', '3행','4행','5행','6행','7행','8행']
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
1행,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
2행,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
3행,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
4행,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
5행,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
6행,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
7행,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
8행,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [16]:
# 인덱스가 하나의 프라이버릿 키 역할을 한다. 
netflix.loc["3행"]

show_id                              3
type                             Movie
title                  Sherlock Holmes
director                   Guy Ritchie
cast                  Robert Downey Jr
country         United States, Germany
release_year                      2009
duration                           128
listed_in           Action & Adventure
Name: 3행, dtype: object

In [17]:
#변수.head(n) 위에서 n개만 갖고온다
netflix.head(3)

,show_id,type,title,director,cast,country,release_year,duration,listed_in
1행,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
2행,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
3행,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure

In [18]:
#변수.tail(n) 뒤에서 n개만 갖고온다
netflix.tail(2)

,show_id,type,title,director,cast,country,release_year,duration,listed_in
7행,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
8행,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [19]:
# 데이터는 몇개고, 타입은 뭐고, 등등
netflix.shape

(8, 9)

In [20]:
netflix.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1행 to 8행
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8 non-null      int64
 1   type          8 non-null      str
 2   title         8 non-null      str
 3   director      5 non-null      str
 4   cast          8 non-null      str
 5   country       6 non-null      str
 6   release_year  8 non-null      int64
 7   duration      8 non-null      int64
 8   listed_in     2 non-null      str
dtypes: int64(3), str(6)
memory usage: 940.0+ bytes

In [21]:
# 1개의 열을 불러올때 1개의 열을 선택할때
title = netflix['title']
# == title = netflix.title
#변수.head() 빈칸이면 기본으로 5개
title.head()

1행                                   Squid Game
2행                              Stranger Things
3행                              Sherlock Holmes
4행    Iron Man & Captain America: Heroes United
5행                                     Bird Box
Name: title, dtype: str

In [22]:
# 2개이상의 열을 선택할때는 [[]]
# 대괄호를 꼭 2개 해줘서 리스트로 만들어줘야된다
title_release_year = netflix[['title','release_year']]
title_release_year.head()

                                        title  release_year
1행                                 Squid Game          2021
2행                            Stranger Things          2019
3행                            Sherlock Holmes          2009
4행  Iron Man & Captain America: Heroes United          2014
5행                                   Bird Box          2018

In [23]:
# 데이터프레임형태로 나타내고 싶으면 대괄호를 2개 써야한다 [[]]
title = netflix[['title']]
title.head()

                                        title
1행                                 Squid Game
2행                            Stranger Things
3행                            Sherlock Holmes
4행  Iron Man & Captain America: Heroes United
5행                                   Bird Box

In [24]:
# 특정 열을 선택하는 목적이 있으면 마찬가지로 특정 행을 선택도 해보고싶다
# SQL의 WHERE절을 데이터프레임으로 이용해서 뽑는단 마인드
netflix = pd.read_csv('./netflix_selena.csv')
netflix['release_year'] > 2015

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7    False
Name: release_year, dtype: bool

In [ ]:
# 저 위에 것을 인덱스로 집어넣는다 
more2015 = netflix[netflix['release_year'] > 2015]
more2015

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN

In [26]:
# 전체를 괄호로 묶어주고 물결표시를 하면 not이라는 뜻이된다
# 범위에 괄호를 잘 설정해주어야한다 
less2015 = netflix[~(netflix['release_year'] > 2015)]
less2015.head()

,show_id,type,title,director,cast,country,release_year,duration,listed_in
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [27]:
# 2015 이후에 나온 컨텐츠 이면서 쇼의 장르가 TV show 인 데이터 추출
type_data = netflix[netflix['type'] == 'TV Show']
type_data2 = type_data[netflix['release_year']>2015]
type_data2

C:\Users\lucky\AppData\Local\Temp\ipykernel_7444\1185418308.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  type_data2 = type_data[netflix['release_year']>2015]

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN

In [ ]:
# 2015 이후에 나온 컨텐츠 이면서 쇼의 장르가 TV show 인 데이터 추출
# and도 아니고 콤마도 아니고 & <<< 이거 이빈다 | << 이거는 or입니다

netflix[(netflix['release_year']>2015) & (netflix['type']== 'TV Show')]

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN

In [29]:
# iloc는 int loction의 줄임말로 무조건 숫자만 써야된다 컬럼 이름을 쓸 수 없다 
# iloc[] >> 무조건 숫자

In [ ]:

title_year = netflix.loc[:,['title', 'release_year']]
title_year.head(2)

             title  release_year
0       Squid Game          2021
1  Stranger Things          2019

In [2]:
# 1,2번째 애들을 프린티 해줌(head 필요 없이)
# 슬라이싱을 통해서 정확한 결과값을 얻어낼 수 잇다
title_year = netflix.loc[0:1,['title', 'release_year']]
title_year

NameError: name 'netflix' is not defined

In [32]:
title_year = netflix.loc[:,['title', 'release_year']]
title_year.head(2)
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [33]:
title_year = netflix.loc[:,['title', 'release_year']]
title_year

                                       title  release_year
0                                 Squid Game          2021
1                            Stranger Things          2019
2                            Sherlock Holmes          2009
3  Iron Man & Captain America: Heroes United          2014
4                                   Bird Box          2018
5                             Anne with an E          2019
6                                 About Time          2013
7                                  Inception          2010

In [34]:
# 인덱싱은 카운팅 안하고 숫자 센다 굳
title_year = netflix.iloc[:,[2, 6]]
title_year

                                       title  release_year
0                                 Squid Game          2021
1                            Stranger Things          2019
2                            Sherlock Holmes          2009
3  Iron Man & Captain America: Heroes United          2014
4                                   Bird Box          2018
5                             Anne with an E          2019
6                                 About Time          2013
7                                  Inception          2010

In [ ]:
# 결측치 확인하기 결측치<< 없는 밸류
# 인포로도 확인가능 결측치를 비율로 확인하는 코드
# 각 컬럼에 결측치가 몇개 있는지 알려주는 함수이다
netflix.isna().sum()

show_id         0
type            0
title           0
director        3
cast            0
country         2
release_year    0
duration        0
listed_in       6
dtype: int64

In [36]:
for i in netflix.columns:
    missingValueRate = netflix[i].isna().sum() / len(netflix) * 100
    if missingValueRate > 0:
        print(f'{i} null rate: {missingValueRate}%')

director null rate: 37.5%
country null rate: 25.0%
listed_in null rate: 75.0%

In [37]:
print(netflix['show_id'].isna().sum())

0

In [38]:
netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country',
       'release_year', 'duration', 'listed_in'],
      dtype='str')

In [39]:
netflix['show_id']

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
Name: show_id, dtype: int64

In [40]:
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
# 결측치 처리 (대체)
# fillna << 결측치만 찾아서 집어넣는다
netflix['country'] = netflix['country'].fillna('No Data')
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,No Data,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
# 결측치 뿐만이 아니다 다른것도 변경가능
netflix['director'] = netflix['director'].replace(np.nan, '박규연')
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,규능아,Lee Jung-jae,No Data,2021,300,NaN
1,2,TV Show,Stranger Things,규능아,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,규능아,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
# .dropna() 값을 대체하는게 아니라 결측치 처리하는 값 - 해당하는 열을 제거해버리는것이다 
# 방향만 나타낼때는 1이 열이다 연산할때는 0이 열이다
# inplace=True 는 원본자체를 없애주고 inplace=False는 그게 아니다 <<<   
netflix.dropna(axis=1, inplace=True)
netflix

,show_id,type,title,director,cast,country,release_year,duration
0,1,TV Show,Squid Game,규능아,Lee Jung-jae,No Data,2021,300
1,2,TV Show,Stranger Things,규능아,Winona Ryder,United States,2019,800
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124
5,6,TV Show,Anne with an E,규능아,Amybeth McNulty,Canada,2019,900
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148

In [60]:
netflix = pd.read_csv("./netflix_selena.csv")
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
#결측치 처리(열 제거) 디렉터에 널값이면 제거하자
# subset = 열을 설정해줘서 그것중에서 dropna << nan 이면 행을 죽이겠다
netflix.dropna(subset=['director'], inplace=True)
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
# 결측치 처리 (특정 열 제거)
if netflix['listed_in'].isna().any():
    netflix.drop(columns=['listed_in'], inplace=True)
netflix

,show_id,type,title,director,cast,country,release_year,duration
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148