In [1]:
import pandas as pd

In [3]:
exam=pd.read_csv('./exam.csv')
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [9]:
#데이터 파악하기
exam.info()
exam.shape

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   nclass   20 non-null     int64
 2   math     20 non-null     int64
 3   english  20 non-null     int64
 4   science  20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes

(20, 5)

In [19]:
# 이런게 다잇네!?!?!?!?!?!?!?
exam.describe()
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [ ]:
# nclass 가 1 인 경우에만 추출을 해줘보자
# exam1 = exam[exam['nclass']==1,['maths']]
# 훨씬더 간편한 방법
exam.query('nclass == 1')

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

In [ ]:
# 1,3,5 반 학생들 출력
exam.query('nclass in [1,3,5]')

InvalidIndexError: (0      True
1      True
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: nclass, dtype: bool, ['maths'])

In [72]:
# 1반 학생들의 수학평균
exam1 = exam.query('nclass == 1')
print(exam1['math'].mean())

46.25

In [75]:
var = 3
exam.query('nclass == @var')

    id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32

In [86]:
# math가 50 이상인 행만 추출한 다음 id,math 추출
exam.query('math >= 50')[['id','math']]

    id  math
0    1    50
1    2    60
5    6    50
6    7    80
7    8    90
9   10    50
10  11    65
14  15    75
15  16    58
16  17    65
17  18    80
18  19    89
19  20    78

In [90]:
# 정렬 하는 내용 order by
# 디폴트 오름차순
exam.sort_values('math', ascending=False)

    id  nclass  math  english  science
7    8       2    90       78       25
18  19       5    89       68       87
6    7       2    80       90       45
17  18       5    80       78       90
19  20       5    78       83       58
14  15       4    75       56       78
10  11       3    65       65       65
16  17       5    65       68       98
1    2       1    60       97       60
15  16       4    58       98       65
0    1       1    50       98       50
5    6       2    50       89       98
9   10       3    50       98       45
13  14       4    48       87       12
12  13       4    46       98       65
2    3       1    45       86       78
11  12       3    45       85       32
3    4       1    30       98       58
4    5       2    25       80       65
8    9       3    20       98       15

In [93]:
exam.sort_values(['nclass','math'], ascending = [True,False])

    id  nclass  math  english  science
1    2       1    60       97       60
0    1       1    50       98       50
2    3       1    45       86       78
3    4       1    30       98       58
7    8       2    90       78       25
6    7       2    80       90       45
5    6       2    50       89       98
4    5       2    25       80       65
10  11       3    65       65       65
9   10       3    50       98       45
11  12       3    45       85       32
8    9       3    20       98       15
14  15       4    75       56       78
15  16       4    58       98       65
13  14       4    48       87       12
12  13       4    46       98       65
18  19       5    89       68       87
17  18       5    80       78       90
19  20       5    78       83       58
16  17       5    65       68       98

In [ ]:
# 파생 컬럼 필요에 따라서 5개에서 6,7개 만들기 
exam.assign(total = exam['math'] + exam['english'] + exam['science'])

    id  nclass  math  english  science  total
0    1       1    50       98       50    198
1    2       1    60       97       60    217
2    3       1    45       86       78    209
3    4       1    30       98       58    186
4    5       2    25       80       65    170
5    6       2    50       89       98    237
6    7       2    80       90       45    215
7    8       2    90       78       25    193
8    9       3    20       98       15    133
9   10       3    50       98       45    193
10  11       3    65       65       65    195
11  12       3    45       85       32    162
12  13       4    46       98       65    209
13  14       4    48       87       12    147
14  15       4    75       56       78    209
15  16       4    58       98       65    221
16  17       5    65       68       98    231
17  18       5    80       78       90    248
18  19       5    89       68       87    244
19  20       5    78       83       58    219

In [107]:
import numpy as np # <<< 기습 입갤 뭐야 얘?!?!!??!!??!!?
#np.where(조건,'조건 만족','조건 만족 X')
exam.assign(test = np.where((exam['math']>=60) | (exam['english'] >=90) , 'pass', 'fail'))

    id  nclass  math  english  science  test
0    1       1    50       98       50  pass
1    2       1    60       97       60  pass
2    3       1    45       86       78  fail
3    4       1    30       98       58  pass
4    5       2    25       80       65  fail
5    6       2    50       89       98  fail
6    7       2    80       90       45  pass
7    8       2    90       78       25  pass
8    9       3    20       98       15  pass
9   10       3    50       98       45  pass
10  11       3    65       65       65  pass
11  12       3    45       85       32  fail
12  13       4    46       98       65  pass
13  14       4    48       87       12  fail
14  15       4    75       56       78  pass
15  16       4    58       98       65  pass
16  17       5    65       68       98  pass
17  18       5    80       78       90  pass
18  19       5    89       68       87  pass
19  20       5    78       83       58  pass

In [109]:
netflix = pd.read_csv('./netflix_cleaned.csv')
netflix

,show_id,type,title,director,cast,country,release_year,duration
0,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300
1,2,TV Show,Stranger Things,No Data,Winona Ryder,United States,2019,800
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124
5,6,TV Show,Anne with an E,No Data,Amybeth McNulty,Canada,2019,900
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148